name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - dev

permissions:
  contents: write  # Needed to push to another branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}  # Use built-in token

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.15.0

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build

      - name: Deploy to master branch
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Create a temporary folder
          mkdir temp-deploy
          cp -r dist/* temp-deploy/
          cd temp-deploy
          echo "learn.mannemlokesh.com" > CNAME

          # Initialize a new Git repo inside dist
          git init
          git checkout -b master
          git add .
          git commit -m "Deploy to GitHub Pages"

          # Force push to master branch
          git push --force "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master